# Generated by Django 5.0.4 on 2024-04-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
