# Generated by Django 5.0.4 on 2024-04-08 07:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_pairing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pairing',
            unique_together={('groupname', 'one', 'two')},
        ),
    ]
